spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    password: root
    username: root
  jpa:
    show-sql: true
eureka:
  client:
    service-url: http://localhost:8761/eureka/
server:
  port: 8084
